server:
  port: 9002
  
  
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microserviceSubject
    username: root
    password: manek24#@tech
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  application:
    name: MicroSubject
    
eureka:
  instance:
    hostname: localhost    